Wait for rtc connection close before create new
raiden-network/raiden pull request #6680
Opened 2020-11-13 10:35 UTC by fredo

## Description

This PR waits for the corresponding greenlet to close a rtc connection before creating a new one. Since they might use the same underlying transport objects of deeper layers connection can turn into a false state if this is done asynchronously

2020-12-02 10:01 UTC, ulope requested changes
Looks mostly good.
Some questions and comments below.

On a general note: We should probably move `r.n.t.m.rtc.utils` and `r.n.t.m.rtc.aiogevent` to a higher package since they can be used independently of webrtc (but we can do that later).

2020-12-02 16:39 UTC, fredo commented on raiden/network/transport/matrix/rtc/utils.py
> +def create_task_callback(
As discussed in private, this will be handled in another PR. Im gonna open an issue for that.

2020-12-02 16:43 UTC, fredo commented on raiden/network/transport/matrix/rtc/web_rtc.py
> +                self._set_local_description(answer),
`set_local_description` also starts gathering candidates which can up to a couple of seconds. We already want to exchange the signaling messages thats why this is outsourced in another task.

2020-12-04 11:48 UTC, ulope commented on raiden/network/transport/matrix/rtc/web_rtc.py
> +                self._set_local_description(answer),
Ah ok

2020-12-04 11:58 UTC, ulope approved these changes
LGTM

2020-12-08 09:02 UTC, merged