Adapt scenarios to use `assert_channel_settled_event` for coop-settle
raiden-network/raiden pull request #7323
Opened 2021-08-25 12:59 UTC by ezdac

Before, there was no coop-settle, so that the settlement of
channels was asserted by querying for a ChannelClosed event.

Coop-settle is now the default mode for a channel closure.
A successful coop-settle life-cycle does not emit a ChannelClosed
event and will remove the channel-state from raiden.
Therefore, the only way to test for a successful coop-settle is
to poll the blockchain for the ChannelSettled event that is
emitted by the coop-settle life-cycle. Additionally, the
uncooperative settle has to be ruled out by asserting that no
ChannelClosed event was emitted on the blockchain.

Depends on: https://github.com/raiden-network/scenario-player/pull/697

2021-08-25 14:41 UTC, netcriptus approved these changes

2021-08-25 14:59 UTC, istankovic commented on raiden/tests/scenarios/bf2_long_running.yaml
> +        tasks:
This is not properly indented.

2021-08-25 14:59 UTC, istankovic requested changes
Needs indentation fix.

2021-08-25 15:07 UTC, istankovic commented on raiden/tests/scenarios/bf2_long_running.yaml
> +        tasks:
Fixed.

2021-08-26 09:13 UTC, istankovic approved these changes

2021-08-26 09:26 UTC, merged