add basic tracing
raiden-network/raiden pull request #7392
Opened 2021-09-30 13:01 UTC by netcriptus

Adding basic Jaeger tracing to the rest api

2021-09-30 13:30 UTC, fredo approved these changes

2021-09-30 14:18 UTC, ulope requested changes
I added some comments below.

This is missing some more pieces though. Let's discuss this in a call.

2021-09-30 14:18 UTC, ulope commented on raiden/ui/cli.py
> +            "--enable-tracing",
With `is_flag=True` you don't need the default

2021-09-30 14:18 UTC, ulope commented on requirements/requirements-ci.txt
> +    #   ipython
`appnope` causes problems on non-mac systems. 
It's an unfortunate issue with pip-compile on cross plattform projects.

I usually just manually delete it from the generated output.

2021-09-30 14:18 UTC, ulope commented on requirements/requirements.in
> +requests-opentracing==0.3.0
Versions shouldn't generally be pinned in the `.in` files (unless there's a very specific reason) as that breaks automatic upgrades (e.g. via dependabot).

2021-09-30 14:18 UTC, ulope commented on raiden/api/python.py
> +            channel_list = self.get_channel_list(registry_address, token_address, partner_address)
The span name doesn't seem to match with the operation that it wraps?
The same with the next two.

2021-09-30 14:18 UTC, ulope commented on raiden/api/rest.py
> +        enable_tracing: bool = False,
Ideally this would be a flag in `RestApiConfig` (and by extension `RaidenConfig` if / when we add tracing to more parts of Raiden)

2021-10-01 08:20 UTC, weilbith commented
Abusing this PR as there is not documentation (yet) how to use this except setting the flag argument: how would this end up being reported? Does it continuously log this or must I stop the node and get a special log somewhere else? Does it just print to stdout during the shutdown? Thanks for helping! 🙏🏾

2021-10-01 11:08 UTC, ulope commented
@weilbith Indeed, this needs docs.

Very quickly:
To enable tracing start raiden with `--enable-tracing`.
Before that start a local `jaeger-agent` (easiest via docker):
```
docker run --rm -it -p 6831:6831/udp jaegertracing/jaeger-agent --reporter.grpc.host-port <jaeger-tracing-server>
```

2021-10-01 11:09 UTC, ulope approved these changes

2021-10-01 16:00 UTC, merged