chore: Add action for automerging patch version updates
raiden-network/raiden pull request #7403
Opened 2021-10-06 16:23 UTC by palango

This should automerge patch upgrades for dependencies

2021-10-07 09:32 UTC, istankovic commented on .github/workflows/auto-merge-dependabot.yml
> +        run: gh pr merge --auto --merge "$PR_URL"
Would this do a merge always? Can we make it do a rebase first?

2021-10-14 14:16 UTC, netcriptus approved these changes

2021-10-14 14:18 UTC, istankovic requested changes
Seems we should rather use `--rebase` (from https://cli.github.com/manual/gh_pr_merge):
```
  -r, --rebase           Rebase the commits onto the base branch
```
That would avoid unnecessary merge commits.

2021-10-14 14:25 UTC, palango commented on .github/workflows/auto-merge-dependabot.yml
> +        run: gh pr merge --auto --merge "$PR_URL"
Done

2021-10-14 14:30 UTC, istankovic approved these changes

2021-10-14 14:39 UTC, merged